my_app_tchat:
    resource: "@MyAppTchatBundle/Resources/config/routing.yml"
    prefix:   /
 
fos_js_routing:
    resource: "@FOSJsRoutingBundle/Resources/config/routing/routing.xml"
    
fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"