my_app_tchat_homepage:
    path:     /index.php 
    defaults: { _controller: MyAppTchatBundle:Default:index }


my_app_tchat_makevu:
    path:     /yu 
    defaults: { _controller: MyAppTchatBundle:Default:makevu }